name: madayen
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  google_fonts: ^0.1.1
  carousel_slider: ^1.4.1
  flutter_slidable: ^0.5.4
  share: ^0.6.2+3
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.6+1
  google_maps_flutter: ^0.5.24
  geolocator: ^5.0.0
  flutter_polyline_points: ^0.1.0
  giffy_dialog: ^1.7.0



  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+6
  firebase_messaging: ^6.0.12




  font_awesome_flutter: ^8.7.0
  cached_network_image: ^2.0.0
  flutter_open_whatsapp: ^0.1.2

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/